uktrade/ci-pipeline

Dockerfile
=> Add python3-pip package to dockerfile

config/export-opportunities.yaml
please review my configuration for export opportunities ci-pipeline
=> Add export opportunities yaml config

config/export-opportunities.yaml
adding a single, non critical, fine to be shared with public env var so that ci-pipeline can pick it up.
=> export opportunities adding a single var for ci-pipeline

config/export-opportunities-worker.yaml
(feature) Add export opportunities worker yaml file config for ci-pipeline
=> Add export opportunities worker yaml config

config/datahub-fe.yaml
As the title says ☝️ 
Envs required for SSO integration on `data-hub-frontend` dev environment
=> add SSO required envs for dev environment

config/datahub-omis-fe.yaml
This sets up omis-fe demo and uat on GOV.UK PaaS.
=> Add omis-fe demo and uat

config/datahub-fe.yaml
UAT is connected to production for testing; will revert to dev once test is complete
=> enabled SSO on all data hub environments

config/datahub-api.yaml
This updates the URLs to the Data Hub frontend and the OMIS frontend in all environments.
=> Update Data Hub API URLs

config/abc.yaml
=> Add ABC to ci pipeline

config/help.yaml
Created new config to deploy enav help to Dev PaaS
=> Add paas deployment for Help Dev

config/export-opportunities.yaml
Zeus is the codename for the next generation Export Opportunities service.
=> add jobs for CD & Staging Zeus environment

config/trade-remedies-api.yaml, config/traderemedies-api.yaml
Includes dev and staging at this point.
=> traderemedies ci pipeline

config/navigator.yaml
[this task](https://uktrade.atlassian.net/browse/ED-3348)
[this task](https://uktrade.atlassian.net/browse/ED-3347)
=> Build index and collect images for navigator

config/navigator.yaml
Reverts uktrade/ci-pipeline#113
=> Revert "Build index and collect images for navigator"

config/lite-address-service.yaml, config/lite-company-verification-service.yaml, config/lite-control-code-service.yaml, config/lite-country-service.yaml, config/lite-customer-service.yaml, config/lite-exporter-dashboard.yaml, config/lite-licence-application.yaml, config/lite-notification-service.yaml, config/lite-ogel-registration.yaml, config/lite-ogel-service.yaml, config/lite-permissions-finder.yaml, config/lite-permissions-service.yaml, config/lite-search-management.yaml, config/lite-user-service.yaml
Full configuration PaaS configuration files for the LITE team.
=> All lite app config files

Jenkinsfile, config/datasci-dt04-input.yaml, config/datasci-dt05-clean.yaml, config/datasci-dt06-algorithm.yaml, config/datasci-dt07-reporting.yaml
=> * improves OC deployement

config/iigb-invest.yaml
For both staging and prod environments
=> Add iigb paas deployment

config/lite-spire-relay-service.yaml
=> Add lite-spire-relay-service

Jenkinsfile
* improve ANSI colouring
* improve network policy API call
* minor improvements on some API/CMD
=> minor improvements

bootstrap.rb, schema.json
=> * simplify vars and secrets parsing

Dockerfile, Jenkinsfile
* cleanup dockerfile
* add goenv support
* remove shallow clone for git submodules
=> improvements

pipeline/db-sync/Jenkinsfile
Stop the ability to use DB as source and destination.
=> fix for duplicate source and destination DB

Jenkinsfile
This adds the ability to do non-rolling deployments, i.e. deployments with downtime. The default was and is still rolling, so all existing pipelines should be unaffected.
While Cloud Foundry rolling deployments are for many apps ideal because they avoid downtime, they don't work with apps that don't have web processes. data-flow now is made up of several apps, including some that don't need to have web processes. They do right now, but this is just so they can be deployed by the existing ci-pipeline code. Having web processes run when they're not used is a bit wasteful, confusing, and potentially a security issue because they could be exposed too easily while also forgotten about
This change means that the web processes of these apps can be scaled to zero, and still deployed by Jenkins, …
=> feat: allow non-rolling deployments
